### ISSUE TITLE
Top-level await is currently not supported with the "cjs" output format

### ISSUE THREAD

**Issue by marianheinsen** [RafidMuhymin/astro-imagetools#37]
I get this error when trying to serve or build the astro project with astro-imagetools:
`..node_modules/astro-imagetools/plugin/index.js:11:48: ERROR: Top-level await is currently not supported with the "cjs" output format`

Astro version: 1.0.0-beta.14
astro-imagetools version: 0.5.6

**astro.config.ts**
```
import { defineConfig } from 'astro/config';
import astroImagePlugin from "astro-imagetools/plugin";

export default defineConfig({
  vite: {
    plugins: [astroImagePlugin],
  },
});
```

**tsconfig.json**

```
{
  "compilerOptions": {
    "module": "ES2022",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
  }
}
```

Does someone know what might be causing the error?

**Comment by RafidMuhymin** [comment]
Oops... Sorry, @marianheinsen I didn't notice that you are using the `.ts` extension. Vite yet hasn't started when Astro picks up the config file. And Node.js treats `.js/.ts` and `.ts/.mts` files differently. The `.js/.ts` files are treated as CJS files and `.mjs/.mts` files are treated as ESM modules. And you can't mix CJS syntax with ESM syntax. So, Node is throwing an error that you can't use import statements, top-level awaits inside CJS files. Changing the extension from `.ts` to `.mts` or `.mjs` should solve this error.

**Comment by marianheinsen** [comment]
@RafidMuhymin Thanks for your reply. Changing the extension of the config file to `.mts` did not fix the issue (same error), however with `.mjs` it works. Would be great to also have this with Typescript working but for now I will stick with `.mjs`. Thanks!
